// Generated by CoffeeScript 2.7.0
(function() {
  var isOperationalError, logError;

  ({logError, isOperationalError} = require('errorhandler'));

  this.attachErrorHandler = function(host) {
    return process.on('unhandledRejection', function(reason, p) {
      return console.error(reason, 'Unhandled Rejection at Promise', p);
    }).on('uncaughtException', function(err) {
      console.error(err, 'Uncaught Exception thrown');
      if (!isOperationalError(err)) {
        return process.exit(1);
      }
    }).on('error', function(err) {
      return console.error(err, 'Error');
    });
  };

  this.wrapErrorHandler = function(o, func, cb) {
    var e;
    try {
      return func(o, cb);
    } catch (error) {
      e = error;
      //console.log " we caught an error!!! "
      console.error(e);
      return cb(e, o);
    }
  };

}).call(this);
